FROM registry.redhat.io/ubi9/nodejs-22:latest@sha256:3e736bfb82137289b9110c1a9406a5e83b209b3527248599300e8ef1a5e3ef81 as builder-ui
 
WORKDIR /opt/app-root/src
USER root

COPY patches patches
COPY jaeger-ui jaeger-ui
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger-ui/LICENSE /licenses/
WORKDIR /opt/app-root/src/jaeger-ui

# add deprecation notice to Jaeger UI
RUN dnf install -y patch
RUN patch -p1 < /opt/app-root/src/patches/jaegerui_deprecation_notice.patch

RUN npm ci --ignore-scripts
RUN npm run build

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23@sha256:0a070e4a8f2698b6aba3630a49eb995ff1b0a182d0c5fa264888acf9d535f384 as builder

WORKDIR /opt/app-root/src
USER root

COPY .git .git
COPY jaeger jaeger
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger/LICENSE /licenses/
WORKDIR /opt/app-root/src/jaeger

COPY --from=builder-ui /opt/app-root/src/jaeger-ui /opt/app-root/src/jaeger-ui

RUN rm -rf ./cmd/query/app/ui/actual && mkdir ./cmd/query/app/ui/actual && cp -r /opt/app-root/src/jaeger-ui/packages/jaeger-ui/build/* ./cmd/query/app/ui/actual/ && find ./cmd/query/app/ui/actual -type f | xargs gzip && \
    exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail VERSION_PKG="github.com/jaegertracing/jaeger/pkg/version" && \
    exportOrFail VERSION_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'` && \
    exportOrFail GIT_LATEST_TAG=`git describe --abbrev=0 --tags` && \
    exportOrFail GIT_COMMIT_SHA=`git rev-parse HEAD` && \
    CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime go build -C ./cmd/query -mod=mod -tags strictfipsruntime,ui \
      -o ./jaeger -trimpath -ldflags "-s -w \
                -X ${VERSION_PKG}.commitSHA=${GIT_COMMIT_SHA} \
                -X ${VERSION_PKG}.latestVersion=${GIT_LATEST_TAG} \
                -X ${VERSION_PKG}.date=${VERSION_DATE}"

FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:b2a1bec3dfbc7a14a1d84d98934dfe8fdde6eb822a211286601cf109cbccb075
WORKDIR /

# For installing RPM updates from lock file
RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf clean all

RUN mkdir /licenses
COPY jaeger/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/jaeger/cmd/query/jaeger /usr/bin/jaeger

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/jaeger"]

LABEL com.redhat.component="jaeger-query-container" \
      name="rhosdt/jaeger-query-rhel8" \
      summary="Jaeger Query" \
      description="This container provides Jaeger UI for Tempo" \
      io.k8s.description="This container provides Jaeger UI for Tempo." \
      io.openshift.expose-services="16686:uihttp" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Jaeger Query"
