FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23@sha256:0a070e4a8f2698b6aba3630a49eb995ff1b0a182d0c5fa264888acf9d535f384 as builder

WORKDIR /opt/app-root/src
USER root

COPY .git .git
COPY api api
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY api/LICENSE /licenses/
WORKDIR /opt/app-root/src/api

RUN CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime go build -mod=mod -tags strictfipsruntime -o tempostack-gateway -trimpath -ldflags "-s -w"

FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:b2a1bec3dfbc7a14a1d84d98934dfe8fdde6eb822a211286601cf109cbccb075
WORKDIR /

RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf install openssl -y && \
    microdnf clean all

RUN mkdir /licenses
COPY api/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/api/tempostack-gateway /usr/bin/tempostack-gateway

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/tempostack-gateway"]

LABEL com.redhat.component="tempo-gateway-container" \
      name="rhosdt/tempo-gateway-rhel8" \
      summary="Tempo Gateway" \
      description="Horizontally-scalable authn/authz-securing reverse proxy for Tempo" \
      io.k8s.description="Horizontally-scalable authn/authz-securing reverse proxy for Tempo." \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Tempo Gateway"
