FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23@sha256:0a070e4a8f2698b6aba3630a49eb995ff1b0a182d0c5fa264888acf9d535f384 as builder

WORKDIR /opt/app-root/src
USER root

COPY .git .git
COPY tempo tempo
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY tempo/LICENSE /licenses/
WORKDIR /opt/app-root/src/tempo

RUN exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail GIT_BRANCH=`git rev-parse --abbrev-ref HEAD` && \
    exportOrFail GIT_REVISION=`git rev-parse --short HEAD` && \
    exportOrFail VERSION=`git describe --tags --abbrev=0 | sed 's/^v//'` && \
    CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime go build -C ./cmd/tempo-query -tags strictfipsruntime -mod vendor \
      -o "tempo-query" -trimpath -ldflags "-s -w -X main.Branch=${GIT_BRANCH} -X main.Revision=${GIT_REVISION} -X main.Version=${VERSION}"

FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:b2a1bec3dfbc7a14a1d84d98934dfe8fdde6eb822a211286601cf109cbccb075
WORKDIR /

RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf install openssl -y && \
    microdnf clean all

RUN mkdir /licenses
COPY tempo/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/tempo/cmd/tempo-query/tempo-query /usr/bin/tempo-query

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/tempo-query"]

LABEL com.redhat.component="tempo-query-container" \
      name="rhosdt/tempo-query-rhel8" \
      summary="Tempo Query" \
      description="This container exposes a Jaeger Query compatible API from Tempo" \
      io.k8s.description="This container exposes a Jaeger Query compatible API from Tempo." \
      io.openshift.expose-services="16686:http,16687:metrics" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Tempo Query"
