FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23@sha256:0a070e4a8f2698b6aba3630a49eb995ff1b0a182d0c5fa264888acf9d535f384 as builder

WORKDIR /opt/app-root/src
USER root

COPY .git .git
COPY patches patches
COPY tempo-operator tempo-operator
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY tempo-operator/LICENSE /licenses/
WORKDIR /opt/app-root/src/tempo-operator

# fix CVE-2025-2786 and CVE-2025-2842
RUN dnf install -y patch
RUN patch -p1 < /opt/app-root/src/patches/subjectaccessreview.patch
RUN patch -p1 < /opt/app-root/src/patches/metrics_role.patch

RUN exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail VERSION_PKG="github.com/grafana/tempo-operator/internal/version" && \
    exportOrFail BUILD_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'` && \
    exportOrFail OPERATOR_VERSION=0.15.4 && \
    exportOrFail COMMIT_SHA=`git rev-parse HEAD` && \
    exportOrFail TEMPO_VERSION=`cat config/manager/manager.yaml | grep -oP "docker.io/grafana/tempo:\K.*"` && \
    exportOrFail TEMPO_QUERY_VERSION=`cat config/manager/manager.yaml | grep -oP "docker.io/grafana/tempo-query:\K.*"` && \
    ls -al && \
    CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime go build -mod=mod -tags strictfipsruntime \
      -o "tempo-operator" -trimpath -ldflags "-s -w \
                -X ${VERSION_PKG}.buildDate=${BUILD_DATE} \
                -X ${VERSION_PKG}.revision=${COMMIT_SHA} \
                -X ${VERSION_PKG}.operatorVersion=${OPERATOR_VERSION} \
                -X ${VERSION_PKG}.tempoVersion=${TEMPO_VERSION} \
                -X ${VERSION_PKG}.tempoQueryVersion=${TEMPO_QUERY_VERSION}" \
                cmd/main.go

FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:b2a1bec3dfbc7a14a1d84d98934dfe8fdde6eb822a211286601cf109cbccb075
WORKDIR /

RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf install openssl -y && \
    microdnf clean all

RUN mkdir /licenses
COPY tempo-operator/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/tempo-operator/tempo-operator /usr/bin/tempo-operator

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/tempo-operator"]

LABEL com.redhat.component="tempo-operator-container" \
      name="rhosdt/tempo-rhel8-operator" \
      summary="Tempo Operator" \
      description="Operator for the Tempo" \
      io.k8s.description="Operator for the Tempo." \
      io.openshift.expose-services="" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Tempo operator"
